import { COMBO_BONUS_AMOUNT, ENERGY_CONFIG } from '../energy/energy.constants';
import {
  STREAK_FREEZE,
  DAILY_QUESTS,
  ENERGY_EARN,
  COMEBACK,
  CHECKIN_REWARDS,
  STREAK_GOALS,
  QUEST_CHEST_FREEZE_FALLBACK_GEMS,
} from '../retention/retention.config';
import {
  GEM_PASSES,
  GEM_PASS_MAX_STACK_DAYS,
} from '../payments/gems/gem-pass.const';
import {
  REFERRAL_GEMS,
  REFERRAL_MILESTONES,
} from '../referral/referral.constants';
import { CHEST_REWARDS } from '../lessons/xp.util';
import {
  DAILY_XP_CAP,
  GRAMMAR_LESSON_CHEST_GEM_SCALE,
  SINGLE_GRANT_XP_CAP,
  STREAK_CHEST_GEMS,
  XP_AWARD_DIVISOR,
} from '../lessons/economy.const';

export type SettingSpec = {
  key: string;
  label: string;
  group: string;
  unit: string;
  min: number;
  max: number;
  integer?: boolean;
  defaultValue: number;
};
const item = (
  key: string,
  label: string,
  group: string,
  unit: string,
  defaultValue: number,
  min: number,
  max: number,
  integer = true,
): SettingSpec => ({
  key,
  label,
  group,
  unit,
  defaultValue,
  min,
  max,
  integer,
});

/** 공개 계약이나 확률 분포를 건드리지 않는, 실제 서버 실행 경로의 숫자만 허용한다. */
export const SETTING_CATALOG: SettingSpec[] = [
  item(
    'ENERGY_CONFIG.MAX',
    '최대 에너지',
    '에너지',
    '개',
    ENERGY_CONFIG.MAX,
    10,
    200,
  ),
  item(
    'ENERGY_CONFIG.FULL_REFILL_HOURS',
    '전체 자연 회복 시간',
    '에너지',
    '시간',
    ENERGY_CONFIG.FULL_REFILL_HOURS,
    1,
    72,
  ),
  item(
    'ENERGY_CONFIG.REFILL_GEM_COST',
    '보석 충전 비용',
    '에너지',
    '보석',
    ENERGY_CONFIG.REFILL_GEM_COST,
    0,
    10000,
  ),
  item(
    'ENERGY_CONFIG.FREE_DAILY_LIMIT',
    '하루 무료 충전 횟수',
    '에너지',
    '회',
    ENERGY_CONFIG.FREE_DAILY_LIMIT,
    0,
    20,
  ),
  item(
    'ENERGY_CONFIG.FREE_AMOUNT',
    '무료 충전량',
    '에너지',
    '개',
    ENERGY_CONFIG.FREE_AMOUNT,
    1,
    100,
  ),
  ...COMBO_BONUS_AMOUNT.map((tier, index) =>
    item(
      `COMBO_BONUS_AMOUNT.${index}.amount`,
      `${index + 1}단계 연속 정답 에너지`,
      '에너지',
      '개',
      tier.amount,
      1,
      10,
    ),
  ),
  item(
    'STREAK_FREEZE.PRICE_GEMS',
    '연속 학습 보호권 가격',
    '연속 학습',
    '보석',
    STREAK_FREEZE.PRICE_GEMS,
    0,
    10000,
  ),
  item(
    'STREAK_FREEZE.MAX_HOLD',
    '보호권 최대 보유',
    '연속 학습',
    '개',
    STREAK_FREEZE.MAX_HOLD,
    1,
    10,
  ),
  item(
    'STREAK_FREEZE.SUPER_WEEKLY',
    'SUPER 주간 보호권',
    '연속 학습',
    '개',
    STREAK_FREEZE.SUPER_WEEKLY,
    0,
    7,
  ),
  ...(['easy', 'normal', 'hard', 'bonus'] as const).map((slot) =>
    item(
      `DAILY_QUESTS.REWARD.${slot}`,
      `${slot} 퀘스트 보상`,
      '일일 퀘스트',
      '보석',
      DAILY_QUESTS.REWARD[slot],
      0,
      1000,
    ),
  ),
  item(
    'DAILY_QUESTS.REROLLS_FREE',
    '무료 사용자 퀘스트 재선택',
    '일일 퀘스트',
    '회',
    DAILY_QUESTS.REROLLS_FREE,
    0,
    10,
  ),
  item(
    'DAILY_QUESTS.REROLLS_SUPER',
    'SUPER 퀘스트 재선택',
    '일일 퀘스트',
    '회',
    DAILY_QUESTS.REROLLS_SUPER,
    0,
    20,
  ),
  item(
    'ENERGY_EARN.PER_CORRECT',
    '오답 복습 정답당 에너지',
    '복습 보상',
    '개',
    ENERGY_EARN.PER_CORRECT,
    0,
    10,
  ),
  item(
    'ENERGY_EARN.SESSION_MAX',
    '복습 1회 에너지 상한',
    '복습 보상',
    '개',
    ENERGY_EARN.SESSION_MAX,
    1,
    50,
  ),
  item(
    'ENERGY_EARN.DAILY_MAX',
    '복습 하루 에너지 상한',
    '복습 보상',
    '개',
    ENERGY_EARN.DAILY_MAX,
    1,
    100,
  ),
  item(
    'COMEBACK.IDLE_DAYS',
    '복귀 보상 비활동 기준',
    '복귀 보상',
    '일',
    COMEBACK.IDLE_DAYS,
    1,
    90,
  ),
  item(
    'COMEBACK.COOLDOWN_DAYS',
    '복귀 보상 재수령 대기',
    '복귀 보상',
    '일',
    COMEBACK.COOLDOWN_DAYS,
    1,
    180,
  ),
  item(
    'COMEBACK.BOOST_MINUTES',
    '복귀 XP 부스트 시간',
    '복귀 보상',
    '분',
    COMEBACK.BOOST_MINUTES,
    1,
    240,
  ),
  item(
    'COMEBACK.XP_MULTIPLIER',
    '복귀 XP 배수',
    '복귀 보상',
    '배',
    COMEBACK.XP_MULTIPLIER,
    1,
    5,
  ),
  ...CHECKIN_REWARDS.map((reward, index) =>
    item(
      `CHECKIN_REWARDS.${index}.gems`,
      `${index + 1}일차 출석 보석`,
      '출석 보상',
      '보석',
      reward.gems,
      0,
      1000,
    ),
  ),
  ...STREAK_GOALS.map((goal, index) =>
    item(
      `STREAK_GOALS.${index}.gems`,
      `${goal.days}일 연속 목표 보석`,
      '연속 학습',
      '보석',
      goal.gems,
      0,
      10000,
    ),
  ),
  ...GEM_PASSES.map((pass, index) =>
    item(
      `GEM_PASSES.${index}.gems`,
      `${pass.days}일 SUPER 이용권 가격`,
      '이용권',
      '보석',
      pass.gems,
      1,
      1000000,
    ),
  ),
  item(
    'GEM_PASS_MAX_STACK_DAYS',
    '이용권 최대 누적 기간',
    '이용권',
    '일',
    GEM_PASS_MAX_STACK_DAYS,
    30,
    365,
  ),
  item(
    'REFERRAL_GEMS',
    '친구 초대 양측 기본 보석',
    '친구 초대',
    '보석',
    REFERRAL_GEMS,
    0,
    10000,
  ),
  ...REFERRAL_MILESTONES.map((milestone, index) =>
    item(
      `REFERRAL_MILESTONES.${index}.gems`,
      `${milestone.count}명 초대 추가 보석`,
      '친구 초대',
      '보석',
      milestone.gems,
      0,
      100000,
    ),
  ),
  item(
    'QUEST_CHEST_FREEZE_FALLBACK_GEMS',
    '보호권 만석 시 상자 대체 보석',
    '상자 보상',
    '보석',
    QUEST_CHEST_FREEZE_FALLBACK_GEMS,
    0,
    1000,
  ),
  item(
    'STREAK_CHEST_GEMS',
    '연속 학습 상자 보석',
    '상자 보상',
    '보석',
    STREAK_CHEST_GEMS,
    0,
    5000,
  ),
  ...(
    [
      ['WOOD_MIN', '나무 상자 최소'],
      ['WOOD_MAX', '나무 상자 최대'],
      ['SILVER_MIN', '은 상자 최소'],
      ['SILVER_MAX', '은 상자 최대'],
      ['GOLD_MIN', '금 상자 최소'],
      ['GOLD_MAX', '금 상자 최대'],
      ['PROGRESS_PER_SECTION', '섹션 진행 보너스'],
      ['PERFECT_BONUS', '무실수 보너스'],
    ] as const
  ).map(([key, label]) =>
    item(
      `CHEST_REWARDS.${key}`,
      label,
      '상자 보상',
      '보석',
      CHEST_REWARDS[key],
      0,
      1000,
    ),
  ),
  item(
    'GRAMMAR_LESSON_CHEST_GEM_SCALE',
    '문법 상자 보석 배율',
    '상자 보상',
    '배',
    GRAMMAR_LESSON_CHEST_GEM_SCALE,
    0.1,
    1,
    false,
  ),
  item(
    'XP_AWARD_DIVISOR',
    '시드 XP 지급 분모',
    'XP',
    '분모',
    XP_AWARD_DIVISOR,
    1,
    10,
  ),
  item('DAILY_XP_CAP', '하루 XP 상한', 'XP', 'XP', DAILY_XP_CAP, 100, 20000),
  item(
    'SINGLE_GRANT_XP_CAP',
    '한 번의 XP 지급 상한',
    'XP',
    'XP',
    SINGLE_GRANT_XP_CAP,
    10,
    5000,
  ),
];

export const settingByKey = new Map(
  SETTING_CATALOG.map((spec) => [spec.key, spec]),
);
