"use client";

import { useEffect, useMemo, useState } from "react";
import { useSession } from "@/features/auth/session";
import { mockAuditSource, type AuditEntry } from "@/shared/data/mock-audit";

type Tab="audit"|"roles";
type Role="super_admin"|"content_admin"|"support"|"analyst";
interface AdminAccount { id:string; email:string; role:Role; lastLogin:string; }
const INITIAL:AdminAccount[]=[{id:"admin-1",email:"admin@korio.demo",role:"super_admin",lastLogin:"2026-10-06 09:20"},{id:"admin-2",email:"content@korio.demo",role:"content_admin",lastLogin:"2026-10-05 18:04"},{id:"admin-3",email:"support@korio.demo",role:"support",lastLogin:"2026-10-05 10:15"},{id:"admin-4",email:"analyst@korio.demo",role:"analyst",lastLogin:"2026-10-04 13:02"}];
const ROLES:Role[]=["super_admin","content_admin","support","analyst"];
const PERMISSIONS=["analytics:read","users:read","users:write","content:read","content:write","subscription:read","subscription:override","operations:write","admin:manage","audit:read"];
const ROLE_ACCESS:Record<Role,string[]>={super_admin:PERMISSIONS,content_admin:["analytics:read","content:read","content:write","users:read"],support:["analytics:read","users:read","users:write","subscription:read"],analyst:["analytics:read","users:read","content:read","subscription:read"]};

export function AdminAuditPage(){
  const {can}=useSession();
  const [tab,setTab]=useState<Tab>("audit");
  const [logs,setLogs]=useState<AuditEntry[]>([]);
  const [query,setQuery]=useState("");
  const [action,setAction]=useState("all");
  const [selected,setSelected]=useState<AuditEntry|null>(null);
  const [admins,setAdmins]=useState(INITIAL);
  const [roleChange,setRoleChange]=useState<{account:AdminAccount;to:Role}|null>(null);
  const [reason,setReason]=useState("");
  const [message,setMessage]=useState("");
  useEffect(()=>{const value=new URLSearchParams(window.location.search).get("tab");if(value==="roles")setTab("roles");mockAuditSource.list().then(setLogs);},[]);
  const filtered=useMemo(()=>logs.filter(row=>(action==="all"||row.action===action)&&`${row.adminEmail} ${row.action} ${row.targetLabel} ${row.reason}`.toLowerCase().includes(query.toLowerCase())),[logs,action,query]);
  const actions=[...new Set(logs.map(row=>row.action))];
  if(!can("audit:read"))return <div className="admin-card admin-empty">감사 로그에 접근할 권한이 없습니다.</div>;
  return <div className="admin-page"><div className="admin-page-head"><div><h2>관리자 · 감사</h2><p>운영 변경의 주체와 사유를 확인합니다. 목록과 역할 변경은 mock 데이터입니다.</p></div><span className="admin-pill blue">Mock Audit</span></div><div className="admin-tabs"><button className={tab==="audit"?"is-active":""} onClick={()=>{setTab("audit");window.history.replaceState(null,"","/admin");void mockAuditSource.list().then(setLogs);}}>감사 로그</button>{can("admin:manage")&&<button className={tab==="roles"?"is-active":""} onClick={()=>{setTab("roles");window.history.replaceState(null,"","/admin?tab=roles");}}>관리자 권한</button>}</div>{message&&<span className="admin-pill blue">{message}</span>}
    {tab==="audit"&&<><div className="admin-toolbar"><input aria-label="감사 로그 검색" placeholder="관리자·대상·사유 검색" value={query} onChange={e=>setQuery(e.target.value)}/><select value={action} onChange={e=>setAction(e.target.value)}><option value="all">모든 행동</option>{actions.map(value=><option key={value} value={value}>{value}</option>)}</select><button onClick={()=>void mockAuditSource.list().then(setLogs)}>새로고침</button></div><section className="admin-card"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>시간</th><th>관리자</th><th>행동</th><th>대상</th><th>사유</th><th>결과</th></tr></thead><tbody>{filtered.map(row=><tr key={row.id} style={{cursor:"pointer"}} onClick={()=>setSelected(row)}><td>{new Date(row.at).toLocaleString("ko-KR")}</td><td>{row.adminEmail}</td><td><strong>{row.action}</strong></td><td>{row.targetLabel||row.targetId}</td><td>{row.reason||"—"}</td><td><span className={`admin-pill ${row.success?"good":"bad"}`}>{row.success?"성공":"실패"}</span></td></tr>)}</tbody></table>{!filtered.length&&<div className="admin-empty">검색 결과가 없습니다.</div>}</div></section></>}
    {tab==="roles"&&can("admin:manage")&&<><section className="admin-card"><div className="admin-card-head"><h3>권한 매트릭스</h3><span className="admin-pill">API의 현재 역할 정책에 맞춘 예시</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Permission</th>{ROLES.map(role=><th key={role}>{role}</th>)}</tr></thead><tbody>{PERMISSIONS.map(permission=><tr key={permission}><td><code>{permission}</code></td>{ROLES.map(role=><td key={role}><span className={`admin-pill ${ROLE_ACCESS[role].includes(permission)?"good":""}`}>{ROLE_ACCESS[role].includes(permission)?"허용":"—"}</span></td>)}</tr>)}</tbody></table></div></section><section className="admin-card"><div className="admin-card-head"><h3>관리자 계정</h3></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>이메일</th><th>역할</th><th>최근 로그인</th><th className="right">변경</th></tr></thead><tbody>{admins.map(account=><tr key={account.id}><td>{account.email}</td><td><span className="admin-pill blue">{account.role}</span></td><td>{account.lastLogin}</td><td className="right"><select aria-label={`${account.email} 역할 변경`} value={account.role} onChange={e=>{setRoleChange({account,to:e.target.value as Role});setReason("");}}>{ROLES.map(role=><option key={role} value={role}>{role}</option>)}</select></td></tr>)}</tbody></table></div></section><p className="page-sub">첫 관리자 부여·비밀번호 설정은 현재 API의 운영 스크립트를 사용합니다. 이 화면의 변경은 mock 상태만 바꿉니다.</p></>}
    {selected&&<div className="admin-drawer-backdrop" onMouseDown={()=>setSelected(null)}><aside className="admin-drawer" onMouseDown={e=>e.stopPropagation()}><button className="btn btn-ghost" onClick={()=>setSelected(null)}>← 닫기</button><h3 style={{marginTop:18}}>{selected.action}</h3><p className="page-sub">{new Date(selected.at).toLocaleString("ko-KR")}</p><div className="admin-detail-grid" style={{marginTop:20}}>{[["관리자",selected.adminEmail],["역할",selected.adminRole],["대상",selected.targetLabel||selected.targetId],["대상 타입",selected.targetType],["IP",selected.ip],["사유",selected.reason||"—"]].map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div><h4 style={{marginTop:24}}>변경 내역</h4><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>필드</th><th>이전</th><th>이후</th></tr></thead><tbody>{Object.entries(selected.changes).map(([field,diff])=><tr key={field}><td>{field}</td><td>{String(diff.from)}</td><td>{String(diff.to)}</td></tr>)}</tbody></table>{!Object.keys(selected.changes).length&&<div className="admin-empty">값 변경 내역이 없습니다.</div>}</div></aside></div>}
    {roleChange&&<div className="admin-modal-backdrop" onMouseDown={()=>setRoleChange(null)}><section className="admin-modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><h3>관리자 역할 변경</h3><p>{roleChange.account.email}: {roleChange.account.role} → {roleChange.to}<br/>실제 권한은 바뀌지 않고 mock 목록에만 반영됩니다.</p><label className="admin-field">변경 사유<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="사유를 입력하세요"/></label><div className="admin-modal-actions"><button className="btn btn-ghost" onClick={()=>setRoleChange(null)}>취소</button><button className="btn btn-primary" disabled={!reason.trim()} onClick={()=>{const {account,to}=roleChange;setAdmins(rows=>rows.map(row=>row.id===account.id?{...row,role:to}:row));void mockAuditSource.record({action:"admin.mock_role_change",targetType:"admin",targetId:account.id,targetLabel:account.email,changes:{role:{from:account.role,to}},reason}).then(()=>mockAuditSource.list().then(setLogs));setMessage("mock 역할만 변경했습니다.");setRoleChange(null);}}>변경</button></div></section></div>}
  </div>;
}
