import { useTranslation } from "react-i18next";

const ko = {
  eyebrow: "SPEAKING STUDIO",
  title: "오늘은 어떤",
  titleAccent: "이야기를 할까요?",
  subtitle: "익숙한 상황부터, 내 목소리로 한국어 한마디.",
  search: "연습하고 싶은 주제 찾기",
  allTopics: "상황별 말하기",
  topicCount: "{{count}}개 주제",
  phrases: "표현 {{count}}개",
  minutes: "약 {{count}}분",
  featured: "오늘의 첫 한마디",
  start: "말하기 시작",
  continue: "이어서 연습",
  emptyTitle: "아직 준비된 주제가 없어요",
  emptyBody: "다른 검색어로 찾아보거나 잠시 후 다시 확인해 주세요.",
  loadError: "주제를 불러오지 못했어요. 다시 시도해 주세요.",
  retry: "다시 시도",
  back: "뒤로",
  tipTitle: "완벽하지 않아도 괜찮아요",
  tipBody: "먼저 듣고, 편하게 따라 말해보세요. 한 문장씩 자신감이 쌓여요.",
  practice: "말하기 연습",
  listen: "문장 듣기",
  listenSlow: "천천히 듣기",
  stopAudio: "듣기 멈추기",
  micStart: "눌러서 말하기",
  micStop: "녹음 끝내기",
  recording: "듣고 있어요",
  processing: "발음을 살펴보고 있어요",
  repeat: "한 번 더",
  skip: "건너뛰기",
  next: "다음 문장",
  finish: "연습 마치기",
  hide: "문장 가리기",
  show: "문장 보기",
  bookmark: "표현 저장",
  saved: "저장한 표현",
  saveFailed: "저장하지 못했어요. 다시 눌러 주세요.",
  translation: "이런 뜻이에요",
  prompt: "뜻을 보고 한국어로 말해보세요",
  readyTitle: "내 목소리로 말해볼까요?",
  readyBody: "먼저 들어보고, 마이크를 눌러 따라 말해보세요.",
  listenTitle: "문장의 리듬을 들어보세요",
  listenBody: "준비되면 마이크를 눌러 내 목소리로 말해보세요.",
  recordingBody: "다 말했으면 가운데 버튼을 한 번 더 눌러 주세요.",
  processingBody: "녹음한 음성에서 발음과 말의 흐름을 확인하고 있어요.",
  goodTitle: "좋아요, 잘 전달됐어요!",
  againTitle: "조금만 더 연습해볼까요?",
  feedbackBody: "단어를 누르면 발음을 다시 들을 수 있어요.",
  accuracy: "정확도",
  fluency: "유창성",
  completeness: "완성도",
  heard: "이렇게 들었어요",
  good: "좋아요",
  improve: "조금 더",
  needsPractice: "다시 연습",
  noSpeech: "목소리가 잘 들리지 않았어요. 마이크 가까이에서 다시 말해 주세요.",
  permission: "말하기 연습을 하려면 마이크 사용을 허용해 주세요.",
  unsupported: "음성 녹음은 Android·iOS 앱에서 사용할 수 있어요. 여기서는 문장을 들어보세요.",
  tooShort: "조금 더 길게 말해 주세요. 문장을 끝까지 읽어보세요.",
  micError: "마이크를 켜지 못했어요. 다시 눌러 주세요.",
  assessError: "발음을 확인하지 못했어요. 잠시 후 다시 말해 주세요.",
  audioError: "음성을 재생하지 못했어요. 다시 눌러 주세요.",
  leaveTitle: "연습을 잠시 멈출까요?",
  leaveBody: "저장한 표현은 유지돼요. 다음에는 주제의 처음부터 연습할 수 있어요.",
  stay: "계속 연습",
  leave: "나가기",
  completeTitle: "오늘도 한 걸음,\n더 자연스럽게.",
  completeBody: "직접 소리 내어 말한 문장이 내 한국어가 돼요.",
  completed: "말해본 문장",
  average: "평균 발음 점수",
  review: "어려웠던 문장 다시 연습",
  topics: "다른 주제 고르기",
  restart: "처음부터 다시",
  sessionCount: "{{current}} / {{total}}",
  score: "발음 점수",
  scoreOutOf: "100점 만점",
  hidden: "문장을 떠올려 보세요",
  errorTitle: "연습을 준비하지 못했어요",
  emptyPractice: "이 주제에 연습할 문장이 아직 없어요.",
  round: "한 문장씩, 나만의 속도로",
  noAttempts: "다음에는 마이크를 눌러 직접 말해보세요.",
  savedNotice: "표현 학습의 저장 목록에서도 볼 수 있어요.",
  microphoneNote: "마이크를 누를 때만 녹음해요",
};

type SpeakingCopy = { [K in keyof typeof ko]: string };

const en: SpeakingCopy = {
  eyebrow: "SPEAKING STUDIO", title: "What shall we", titleAccent: "talk about today?",
  subtitle: "Everyday moments. A little more Korean, in your own voice.",
  search: "Find a topic to practise", allTopics: "Everyday conversations", topicCount: "{{count}} topics",
  phrases: "{{count}} phrases", minutes: "About {{count}} min", featured: "YOUR FIRST WORDS TODAY",
  start: "Let's speak", continue: "Keep practising", emptyTitle: "No topics here yet",
  emptyBody: "Try another search or check back in a little while.",
  loadError: "We couldn't load the topics. Please try again.", retry: "Try again", back: "Back",
  tipTitle: "It doesn't have to be perfect", tipBody: "Listen first, then give it a go. Confidence grows one sentence at a time.",
  practice: "Speaking practice", listen: "Listen", listenSlow: "Listen slowly", stopAudio: "Stop listening",
  micStart: "Tap to speak", micStop: "Finish recording", recording: "I'm listening", processing: "Checking your pronunciation",
  repeat: "Try once more", skip: "Skip", next: "Next phrase", finish: "Finish practice", hide: "Hide phrase", show: "Show phrase",
  bookmark: "Save phrase", saved: "Saved phrase", saveFailed: "Couldn't save. Please tap again.",
  translation: "WHAT IT MEANS", prompt: "Say this in Korean", readyTitle: "Ready to make it yours?",
  readyBody: "Listen first, then tap the microphone and say it out loud.",
  listenTitle: "Listen to the rhythm", listenBody: "When you're ready, tap the microphone and give it a go.",
  recordingBody: "Tap the centre button again when you've finished.", processingBody: "Listening for clear sounds and a natural flow.",
  goodTitle: "Lovely, that came through!", againTitle: "Let's give it another go", feedbackBody: "Tap a word to hear it again.",
  accuracy: "Accuracy", fluency: "Fluency", completeness: "Completeness", heard: "WHAT WE HEARD",
  good: "Clear", improve: "Almost", needsPractice: "Practise again",
  noSpeech: "We couldn't hear you clearly. Move closer to the microphone and try again.",
  permission: "Please allow microphone access to practise speaking.",
  unsupported: "Recording is available in the Android and iOS app. You can listen to phrases here.",
  tooShort: "Try speaking a little longer. Say the whole sentence.", micError: "Couldn't start the microphone. Please try again.",
  assessError: "Couldn't check your pronunciation. Please try again shortly.", audioError: "Couldn't play the audio. Please try again.",
  leaveTitle: "Take a break?", leaveBody: "Saved phrases stay saved. Next time you can start this topic again.", stay: "Keep practising", leave: "Leave",
  completeTitle: "A little braver.\nA little more fluent.", completeBody: "Every sentence you say out loud becomes a little more yours.",
  completed: "Phrases spoken", average: "Average pronunciation", review: "Revisit tricky phrases", topics: "Explore more topics", restart: "Start again",
  sessionCount: "{{current}} / {{total}}", score: "Pronunciation", scoreOutOf: "out of 100", hidden: "Try to remember the phrase",
  errorTitle: "Couldn't prepare your practice", emptyPractice: "There aren't any phrases in this topic yet.", round: "One phrase at a time. At your own pace.",
  noAttempts: "Next time, tap the microphone and give speaking a go.", savedNotice: "You'll also find it in your saved expressions.", microphoneNote: "Recording starts only when you tap the mic",
};

const uz: SpeakingCopy = {
  eyebrow: "SPEAKING STUDIO", title: "Bugun nima haqida", titleAccent: "gaplashamiz?",
  subtitle: "Kundalik vaziyatlarda koreyscha gapiring. O‘z ovozingiz bilan.",
  search: "Mashq uchun mavzu topish", allTopics: "Kundalik suhbatlar", topicCount: "{{count}} ta mavzu",
  phrases: "{{count}} ta ibora", minutes: "Taxminan {{count}} daqiqa", featured: "BUGUNGI ILK SO‘ZLAR",
  start: "Gapirishni boshlash", continue: "Davom etish", emptyTitle: "Hozircha mavzular yo‘q",
  emptyBody: "Boshqa so‘z bilan qidiring yoki birozdan keyin qayta tekshiring.",
  loadError: "Mavzularni yuklab bo‘lmadi. Qayta urinib ko‘ring.", retry: "Qayta urinish", back: "Orqaga",
  tipTitle: "Mukammal bo‘lishi shart emas", tipBody: "Avval tinglang, keyin bemalol takrorlang. Har bir jumla bilan ishonch ortadi.",
  practice: "Gapirish mashqi", listen: "Tinglash", listenSlow: "Sekin tinglash", stopAudio: "Tinglashni to‘xtatish",
  micStart: "Bosib gapiring", micStop: "Yozishni tugatish", recording: "Sizni tinglayapman", processing: "Talaffuz tekshirilmoqda",
  repeat: "Yana bir marta", skip: "O‘tkazish", next: "Keyingi jumla", finish: "Mashqni tugatish", hide: "Jumlani yashirish", show: "Jumlani ko‘rish",
  bookmark: "Iborani saqlash", saved: "Saqlangan ibora", saveFailed: "Saqlanmadi. Qayta bosing.",
  translation: "MA’NOSI", prompt: "Buni koreyscha ayting", readyTitle: "O‘z ovozingiz bilan aytasizmi?",
  readyBody: "Avval tinglang, keyin mikrofonni bosib takrorlang.",
  listenTitle: "Jumla ohangiga quloq tuting", listenBody: "Tayyor bo‘lsangiz, mikrofonni bosib ayting.",
  recordingBody: "Gapirib bo‘lgach, o‘rtadagi tugmani yana bosing.", processingBody: "Talaffuz va nutqingiz ravonligini tekshiryapmiz.",
  goodTitle: "Zo‘r, juda tushunarli!", againTitle: "Yana bir mashq qilamizmi?", feedbackBody: "So‘zni bosib talaffuzini qayta eshiting.",
  accuracy: "Aniqlik", fluency: "Ravonlik", completeness: "To‘liqlik", heard: "ESHITGANIMIZ",
  good: "Yaxshi", improve: "Deyarli", needsPractice: "Mashq qiling",
  noSpeech: "Ovozingiz aniq eshitilmadi. Mikrofonga yaqinroq kelib qayta ayting.",
  permission: "Gapirish mashqi uchun mikrofondan foydalanishga ruxsat bering.",
  unsupported: "Ovoz yozish Android va iOS ilovasida ishlaydi. Bu yerda jumlalarni tinglashingiz mumkin.",
  tooShort: "Biroz uzunroq gapiring. Jumlani oxirigacha ayting.", micError: "Mikrofonni yoqib bo‘lmadi. Qayta urinib ko‘ring.",
  assessError: "Talaffuzni tekshirib bo‘lmadi. Birozdan keyin qayta ayting.", audioError: "Ovozni ijro etib bo‘lmadi. Qayta bosing.",
  leaveTitle: "Biroz tanaffus qilasizmi?", leaveBody: "Saqlangan iboralar qoladi. Keyingi safar mavzuni boshidan boshlashingiz mumkin.", stay: "Davom etish", leave: "Chiqish",
  completeTitle: "Har bir jumla bilan\nyanada ravonroq.", completeBody: "Ovoz chiqarib aytgan har bir jumla koreyschangizni mustahkamlaydi.",
  completed: "Aytilgan jumlalar", average: "O‘rtacha talaffuz", review: "Qiyin jumlalarni takrorlash", topics: "Boshqa mavzuni tanlash", restart: "Qayta boshlash",
  sessionCount: "{{current}} / {{total}}", score: "Talaffuz", scoreOutOf: "100 balldan", hidden: "Jumlani eslab ko‘ring",
  errorTitle: "Mashqni tayyorlab bo‘lmadi", emptyPractice: "Bu mavzuda hali mashq jumlalari yo‘q.", round: "Bittadan jumla. O‘zingizga qulay tezlikda.",
  noAttempts: "Keyingi safar mikrofonni bosib, o‘zingiz aytib ko‘ring.", savedNotice: "Uni saqlangan iboralar ro‘yxatidan ham topasiz.", microphoneNote: "Faqat mikrofon bosilganda ovoz yoziladi",
};

const ru: SpeakingCopy = {
  eyebrow: "SPEAKING STUDIO", title: "О чём поговорим", titleAccent: "сегодня?",
  subtitle: "Знакомые ситуации. Корейский вашим голосом.",
  search: "Найти тему для практики", allTopics: "Повседневные разговоры", topicCount: "Тем: {{count}}",
  phrases: "Фраз: {{count}}", minutes: "Около {{count}} мин", featured: "ПЕРВЫЕ СЛОВА СЕГОДНЯ",
  start: "Начать говорить", continue: "Продолжить", emptyTitle: "Тем пока нет",
  emptyBody: "Попробуйте другой запрос или загляните чуть позже.",
  loadError: "Не удалось загрузить темы. Попробуйте ещё раз.", retry: "Повторить", back: "Назад",
  tipTitle: "Не обязательно говорить идеально", tipBody: "Сначала послушайте, затем повторите. Уверенность растёт с каждой фразой.",
  practice: "Практика речи", listen: "Послушать", listenSlow: "Послушать медленно", stopAudio: "Остановить звук",
  micStart: "Нажмите и говорите", micStop: "Завершить запись", recording: "Слушаю вас", processing: "Проверяем произношение",
  repeat: "Ещё раз", skip: "Пропустить", next: "Следующая фраза", finish: "Завершить", hide: "Скрыть фразу", show: "Показать фразу",
  bookmark: "Сохранить фразу", saved: "Сохранённая фраза", saveFailed: "Не удалось сохранить. Нажмите ещё раз.",
  translation: "ЗНАЧЕНИЕ", prompt: "Скажите это по-корейски", readyTitle: "Попробуем вашим голосом?",
  readyBody: "Сначала послушайте, затем нажмите микрофон и повторите.",
  listenTitle: "Прислушайтесь к ритму", listenBody: "Когда будете готовы, нажмите микрофон и произнесите фразу.",
  recordingBody: "Закончив говорить, нажмите центральную кнопку ещё раз.", processingBody: "Проверяем звуки и плавность вашей речи.",
  goodTitle: "Отлично, всё понятно!", againTitle: "Попробуем ещё раз?", feedbackBody: "Нажмите на слово, чтобы послушать его ещё раз.",
  accuracy: "Точность", fluency: "Беглость", completeness: "Полнота", heard: "МЫ УСЛЫШАЛИ",
  good: "Хорошо", improve: "Почти", needsPractice: "Повторите",
  noSpeech: "Вас плохо слышно. Поднесите микрофон ближе и повторите.",
  permission: "Разрешите доступ к микрофону для практики речи.",
  unsupported: "Запись доступна в приложении на Android и iOS. Здесь можно слушать фразы.",
  tooShort: "Говорите немного дольше. Произнесите всё предложение.", micError: "Не удалось включить микрофон. Попробуйте ещё раз.",
  assessError: "Не удалось проверить произношение. Попробуйте чуть позже.", audioError: "Не удалось воспроизвести звук. Нажмите ещё раз.",
  leaveTitle: "Сделаем перерыв?", leaveBody: "Сохранённые фразы останутся. В следующий раз можно начать тему заново.", stay: "Продолжить", leave: "Выйти",
  completeTitle: "С каждой фразой\nвсё увереннее.", completeBody: "Каждая фраза вслух помогает сделать корейский своим.",
  completed: "Произнесено фраз", average: "Средняя оценка", review: "Повторить сложные фразы", topics: "Выбрать другую тему", restart: "Начать заново",
  sessionCount: "{{current}} / {{total}}", score: "Произношение", scoreOutOf: "из 100", hidden: "Попробуйте вспомнить фразу",
  errorTitle: "Не удалось подготовить практику", emptyPractice: "В этой теме пока нет фраз для практики.", round: "По одной фразе. В своём темпе.",
  noAttempts: "В следующий раз нажмите микрофон и попробуйте сами.", savedNotice: "Она также доступна в списке сохранённых выражений.", microphoneNote: "Запись начинается только по нажатию микрофона",
};

const copies: Record<string, SpeakingCopy> = { ko, en, uz, ru };

export function useSpeakingCopy(): SpeakingCopy {
  const { i18n } = useTranslation();
  return copies[(i18n.resolvedLanguage || i18n.language || "uz").split("-")[0]] ?? en;
}

export function formatSpeaking(text: string, values: Record<string, string | number>) {
  return text.replace(/\{\{(\w+)\}\}/g, (_, key: string) => String(values[key] ?? ""));
}
