"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { mockAuditSource } from "@/shared/data/mock-audit";
import { mockContentRepository, newQuestion } from "./mock-repository";
import {
  LANGUAGES, QUESTION_TYPES, type ContentLesson, type ContentSnapshot,
  type GrammarItem, type ExpressionItem, type LibraryItem,
  type LocalizedText, type QuestionDraft, type QuestionType, localized,
} from "./types";
import s from "./content-page.module.css";

type Tab = "path" | "questions" | "quality" | "library" | "localization";
const TABS: { key: Tab; label: string }[] = [
  { key: "path", label: "학습 경로" }, { key: "questions", label: "문제 관리" },
  { key: "quality", label: "문제 품질" }, { key: "library", label: "Grammar · Expressions · Hangul" },
  { key: "localization", label: "번역 상태" },
];
const TYPE_LABEL: Record<QuestionType, string> = {
  sentence_builder: "뜻 조립", translate_builder: "번역 조립", word_arrange: "어절 배열", speaking: "말하기",
  image_choice: "그림 선택", dialog_complete: "대화 완성", type_answer: "단어 입력", word_matching: "단어 매칭",
  listening: "듣기", fill_in_blank: "빈칸", listen_type: "듣고 쓰기", listen_fill: "듣고 빈칸",
  translate_type: "번역 입력", audio_match: "오디오 매칭", grammar_blank: "문법 빈칸", grammar_build: "문법 조립",
  reply_builder: "대답 조립", reading_quiz: "독해", error_hunt: "오류 찾기", cloze_passage: "지문 빈칸",
  dialog_order: "대화 순서", verb_transform: "동사 활용",
};
const clone = <T,>(value: T): T => structuredClone(value);
const split = (text: string) => text.split("\n").map(item => item.trim()).filter(Boolean);
const join = (items: string[]) => items.join("\n");
const coverage = (value: LocalizedText) => LANGUAGES.filter(lang => value[lang].trim()).length;
const auditChange = (action: string, targetType: string, targetId: string, targetLabel: string, from: unknown, to: unknown, reason = "") => {
  const changes: Record<string, { from: unknown; to: unknown }> = {};
  if (from && to && typeof from === "object" && typeof to === "object") {
    const before = from as Record<string, unknown>;
    const after = to as Record<string, unknown>;
    for (const key of Object.keys(after)) {
      if (key !== "metrics" && JSON.stringify(before[key]) !== JSON.stringify(after[key])) changes[key] = { from: before[key], to: after[key] };
    }
  } else changes.record = { from, to };
  return mockAuditSource.record({ action, targetType, targetId, targetLabel, changes, reason });
};

export function ContentPage() {
  const router = useRouter();
  const params = useSearchParams();
  const requested = params.get("tab");
  const tab: Tab = TABS.some(item => item.key === requested) ? requested as Tab : "path";
  const [data, setData] = useState<ContentSnapshot | null>(null);
  const [error, setError] = useState("");
  const [selectedLessonId, setSelectedLessonId] = useState("l1");
  const [selectedQuestionId, setSelectedQuestionId] = useState("q1");
  const [selectedLibraryId, setSelectedLibraryId] = useState("g1");
  const [lessonDraft, setLessonDraft] = useState<ContentLesson | null>(null);
  const [questionDraft, setQuestionDraft] = useState<QuestionDraft | null>(null);
  const [libraryDraft, setLibraryDraft] = useState<LibraryItem | null>(null);
  const [confirm, setConfirm] = useState<{ kind: "lesson" | "question"; id: string; label: string } | null>(null);
  const [reason, setReason] = useState("");
  const [saving, setSaving] = useState(false);
  const [notice, setNotice] = useState("");

  useEffect(() => { mockContentRepository.load().then(setData).catch(() => setError("MOCK_LOAD_FAILED")); }, []);
  useEffect(() => { if (data && selectedLessonId && !lessonDraft) setLessonDraft(clone(data.lessons.find(item => item.id === selectedLessonId) ?? data.lessons[0] ?? null)); }, [data, selectedLessonId, lessonDraft]);
  useEffect(() => { if (data && selectedQuestionId && !questionDraft) setQuestionDraft(clone(data.questions.find(item => item.id === selectedQuestionId) ?? data.questions[0] ?? null)); }, [data, selectedQuestionId, questionDraft]);
  useEffect(() => { if (data && selectedLibraryId && !libraryDraft) setLibraryDraft(clone(data.library.find(item => item.id === selectedLibraryId) ?? data.library[0] ?? null)); }, [data, selectedLibraryId, libraryDraft]);

  const selectLesson = (id: string) => { setSelectedLessonId(id); setLessonDraft(data ? clone(data.lessons.find(item => item.id === id) ?? data.lessons[0] ?? null) : null); };
  const selectQuestion = (id: string) => { setSelectedQuestionId(id); setQuestionDraft(data ? clone(data.questions.find(item => item.id === id) ?? data.questions[0] ?? null) : null); };
  const selectLibrary = (id: string) => { setSelectedLibraryId(id); setLibraryDraft(data ? clone(data.library.find(item => item.id === id) ?? data.library[0] ?? null) : null); };
  const changeTab = (next: Tab) => router.push(next === "path" ? "/content" : `/content?tab=${next}`);
  const commit = async (work: () => Promise<ContentSnapshot>, message: string, audit?: (next: ContentSnapshot) => Promise<unknown>) => {
    setSaving(true); setError("");
    try { const next = await work(); setData(next); if (audit) await audit(next); setNotice(`${message} · mock 데이터에만 반영됨`); }
    catch { setError("MOCK_SAVE_FAILED"); }
    finally { setSaving(false); }
  };

  if (error && !data) return <div className="admin-card admin-empty">콘텐츠를 불러오지 못했습니다. {error}<button className={s.button} onClick={() => mockContentRepository.load().then(setData)}>다시 시도</button></div>;
  if (!data) return <div className="admin-card admin-empty">콘텐츠를 불러오는 중…</div>;

  return <div className="admin-page">
    <div className="admin-page-head"><div><h2>Content Management</h2><p>실제 KORIO 스키마를 기준으로 구성한 편집용 mock 워크스페이스</p></div><span className="admin-pill blue">LOCAL MOCK · 서버에 저장되지 않음</span></div>
    <nav className="admin-tabs" aria-label="콘텐츠 관리 탭">{TABS.map(item => <button key={item.key} className={tab === item.key ? "is-active" : ""} onClick={() => changeTab(item.key)}>{item.label}</button>)}</nav>
    {notice && <div className={s.notice} role="status">{notice}<button aria-label="알림 닫기" onClick={() => setNotice("")}>×</button></div>}
    {error && <div className={s.error} role="alert">{error}</div>}
    {tab === "path" && <PathTab data={data} draft={lessonDraft} setDraft={setLessonDraft} selectLesson={selectLesson} onSave={() => lessonDraft && commit(() => mockContentRepository.saveLesson(lessonDraft), "레슨 저장 완료", () => auditChange("lesson.update", "lesson", lessonDraft.id, lessonDraft.title.ko, data.lessons.find(item => item.id === lessonDraft.id) ?? null, lessonDraft))} onReorder={(id, target) => commit(() => mockContentRepository.reorderLesson(id, target), "레슨 순서 변경 완료", next => auditChange("lesson.reorder", "lesson", id, data.lessons.find(item => item.id === id)?.title.ko ?? id, data.lessons.find(item => item.id === id)?.order, next.lessons.find(item => item.id === id)?.order))} onCreate={() => {
      const node = data.nodes.find(item => item.nodeType === "lesson")!;
      const next: ContentLesson = { id: `l-${Date.now()}`, code: `new-lesson-${Date.now()}`, nodeId: node.id, title: localized("새 레슨"), description: localized(""), category: node.category ?? "vocabulary", level: "1", section: node.section, unit: node.unit, order: data.lessons.filter(item => item.nodeId === node.id).length + 1, xpReward: 40, isActive: false };
      setSelectedLessonId(next.id); setLessonDraft(next);
    }} onDelete={() => lessonDraft && setConfirm({ kind: "lesson", id: lessonDraft.id, label: lessonDraft.title.ko })} onQuestion={id => { selectQuestion(id); changeTab("questions"); }} saving={saving}/>}
    {tab === "questions" && <QuestionsTab data={data} draft={questionDraft} setDraft={setQuestionDraft} select={selectQuestion} onSave={() => questionDraft && commit(() => mockContentRepository.saveQuestion(questionDraft), "문제 저장 완료", () => auditChange("question.update", "question", questionDraft.id, questionDraft.code, data.questions.find(item => item.id === questionDraft.id) ?? null, questionDraft))} onCreate={() => { const next = newQuestion("translate_builder", data.lessons[0]?.id, data.questions.length + 1); setSelectedQuestionId(next.id); setQuestionDraft(next); }} onDuplicate={() => { if (!questionDraft) return; const next = clone(questionDraft); next.id = `q-${Date.now()}`; next.code = `${questionDraft.code}-copy-${Date.now().toString().slice(-4)}`; next.order += 1; next.metrics = { attempts: 0, correctRate: 0, skipRate: 0, avgDurationMs: 0, dropOffRate: 0 }; next.isActive = false; setSelectedQuestionId(next.id); setQuestionDraft(next); }} onDelete={() => questionDraft && setConfirm({ kind: "question", id: questionDraft.id, label: questionDraft.code })} onReorder={(id, target) => commit(() => mockContentRepository.reorderQuestion(id, target), "문제 순서 변경 완료", next => auditChange("question.reorder", "question", id, data.questions.find(item => item.id === id)?.code ?? id, data.questions.find(item => item.id === id)?.order, next.questions.find(item => item.id === id)?.order))} saving={saving}/>}
    {tab === "quality" && <QualityTab data={data} onQuestion={id => { selectQuestion(id); changeTab("questions"); }}/>}
    {tab === "library" && <LibraryTab data={data} draft={libraryDraft} setDraft={setLibraryDraft} select={selectLibrary} onSave={() => libraryDraft && commit(() => mockContentRepository.saveLibraryItem(libraryDraft), "콘텐츠 저장 완료", () => auditChange(`${libraryDraft.kind}.update`, libraryDraft.kind, libraryDraft.id, libraryDraft.kind === "grammar" ? libraryDraft.pattern : libraryDraft.kind === "expression" ? libraryDraft.korean : libraryDraft.char, data.library.find(item => item.id === libraryDraft.id) ?? null, libraryDraft))} saving={saving}/>}
    {tab === "localization" && <LocalizationTab data={data} onQuestion={id => { selectQuestion(id); changeTab("questions"); }} onLibrary={id => { selectLibrary(id); changeTab("library"); }} onLesson={id => { selectLesson(id); changeTab("path"); }}/>}
    {confirm && <div className="admin-modal-backdrop" onMouseDown={() => setConfirm(null)}><div className="admin-modal" role="dialog" aria-modal="true" aria-label="삭제 확인" onMouseDown={event => event.stopPropagation()}><h3>{confirm.kind === "lesson" ? "레슨" : "문제"} 삭제</h3><p><strong>{confirm.label}</strong>을 mock 목록에서 삭제합니다. 레슨을 삭제하면 연결된 mock 문제도 함께 삭제됩니다. 삭제 이유를 남겨주세요.</p><label className="admin-field">삭제 이유<textarea value={reason} onChange={event => setReason(event.target.value)} placeholder="운영 기록용 이유" /></label><div className="admin-modal-actions"><button className={s.button} onClick={() => { setConfirm(null); setReason(""); }}>취소</button><button className={s.dangerButton} disabled={!reason.trim() || saving} onClick={async () => { const target = confirm; const before = target.kind === "lesson" ? data.lessons.find(item => item.id === target.id) : data.questions.find(item => item.id === target.id); await commit(() => target.kind === "lesson" ? mockContentRepository.deleteLesson(target.id) : mockContentRepository.deleteQuestion(target.id), "삭제 완료", () => auditChange(`${target.kind}.delete`, target.kind, target.id, target.label, before ?? null, null, reason.trim())); setConfirm(null); setReason(""); if (target.kind === "lesson") { setSelectedLessonId(""); setLessonDraft(null); } else { setSelectedQuestionId(""); setQuestionDraft(null); } }}>삭제</button></div></div></div>}
  </div>;
}

function TranslationFields({ label, value, onChange }: { label: string; value: LocalizedText; onChange: (value: LocalizedText) => void }) {
  return <fieldset className={s.translations}><legend>{label}</legend><div className={s.translationGrid}>{LANGUAGES.map(lang => <label key={lang} className="admin-field">{lang.toUpperCase()} <span className={value[lang].trim() ? s.goodText : s.badText}>{value[lang].trim() ? "✓" : "누락"}</span><input value={value[lang]} onChange={event => onChange({ ...value, [lang]: event.target.value })}/></label>)}</div></fieldset>;
}

function PathTab({ data, draft, setDraft, selectLesson, onSave, onReorder, onCreate, onDelete, onQuestion, saving }: {
  data: ContentSnapshot; draft: ContentLesson | null; setDraft: (draft: ContentLesson) => void; selectLesson: (id: string) => void;
  onSave: () => void; onReorder: (id: string, targetId: string) => void; onCreate: () => void; onDelete: () => void; onQuestion: (id: string) => void; saving: boolean;
}) {
  const [collapsed, setCollapsed] = useState<string[]>([]);
  const [dragId, setDragId] = useState("");
  const toggle = (key: string) => setCollapsed(current => current.includes(key) ? current.filter(item => item !== key) : [...current, key]);
  const sections = [...new Set(data.nodes.map(item => item.section))].sort((a, b) => a - b);
  return <div className={s.pathLayout}>
    <section className="admin-card"><div className="admin-card-head"><h3>학습 경로</h3><button className={s.primaryButton} onClick={onCreate}>+ 레슨</button></div><div className={s.tree}>
      {sections.map(section => <div key={section}><button className={s.treeGroup} onClick={() => toggle(`s${section}`)}>{collapsed.includes(`s${section}`) ? "▸" : "▾"} Section {section}</button>{!collapsed.includes(`s${section}`) && [...new Set(data.nodes.filter(node => node.section === section).map(node => node.unit))].sort((a, b) => a - b).map(unit => <div key={unit} className={s.treeIndent}><button className={s.treeGroup} onClick={() => toggle(`s${section}u${unit}`)}>{collapsed.includes(`s${section}u${unit}`) ? "▸" : "▾"} Unit {unit}</button>{!collapsed.includes(`s${section}u${unit}`) && data.nodes.filter(node => node.section === section && node.unit === unit).sort((a, b) => a.order - b.order).map(node => <div key={node.id} className={s.treeIndent}><button className={s.treeNode} onClick={() => toggle(node.id)}>{collapsed.includes(node.id) ? "▸" : "▾"} {node.title.ko} <small>{node.nodeType}</small></button>{!collapsed.includes(node.id) && data.lessons.filter(lesson => lesson.nodeId === node.id).sort((a, b) => a.order - b.order).map(lesson => <button key={lesson.id} draggable onDragStart={() => setDragId(lesson.id)} onDragOver={event => event.preventDefault()} onDrop={event => { event.preventDefault(); if (dragId && dragId !== lesson.id) onReorder(dragId, lesson.id); setDragId(""); }} className={`${s.treeLesson} ${draft?.id === lesson.id ? s.selected : ""}`} onClick={() => selectLesson(lesson.id)}>{lesson.order}. {lesson.title.ko}<span className={lesson.isActive ? s.statusOn : s.statusOff}>{lesson.isActive ? "●" : "○"}</span></button>)}</div>)}</div>)}</div>)}
    </div></section>
    <section className="admin-card">{draft ? <><div className="admin-card-head"><div><h3>{draft.title.ko || "새 레슨"}</h3><small className={s.muted}>{draft.code} · {draft.category} · Level {draft.level}</small></div><div className={s.actions}><button className={s.button} onClick={onDelete}>삭제</button><button className={s.primaryButton} disabled={saving} onClick={onSave}>저장</button></div></div><div className="admin-card-body">
      <div className={s.formGrid}><label className="admin-field">고유 코드<input value={draft.code} onChange={event => setDraft({ ...draft, code: event.target.value })}/></label><label className="admin-field">연결 노드<select value={draft.nodeId} onChange={event => { const node = data.nodes.find(item => item.id === event.target.value)!; setDraft({ ...draft, nodeId: node.id, section: node.section, unit: node.unit, category: node.category ?? draft.category }); }}>{data.nodes.filter(node => node.nodeType === "lesson").map(node => <option key={node.id} value={node.id}>S{node.section} · U{node.unit} · {node.title.ko}</option>)}</select></label><label className="admin-field">카테고리<select value={draft.category} onChange={event => setDraft({ ...draft, category: event.target.value as ContentLesson["category"] })}>{["vocabulary", "grammar", "expression", "conversation", "listening", "topik"].map(value => <option key={value}>{value}</option>)}</select></label><label className="admin-field">레벨<select value={draft.level} onChange={event => setDraft({ ...draft, level: event.target.value as ContentLesson["level"] })}>{["1", "2", "3", "4", "5", "6"].map(value => <option key={value}>{value}</option>)}</select></label><label className="admin-field">노드 내 순서<input type="number" min={1} value={draft.order} onChange={event => setDraft({ ...draft, order: Number(event.target.value) })}/></label><label className="admin-field">XP 보상<input type="number" min={0} value={draft.xpReward} onChange={event => setDraft({ ...draft, xpReward: Number(event.target.value) })}/></label><label className="admin-field">문법 코드<input value={draft.grammarCode ?? ""} onChange={event => setDraft({ ...draft, grammarCode: event.target.value })} placeholder="문법 레슨 전용"/></label><label className="admin-field">상태<select value={draft.isActive ? "active" : "inactive"} onChange={event => setDraft({ ...draft, isActive: event.target.value === "active" })}><option value="active">활성</option><option value="inactive">비활성</option></select></label></div>
      <TranslationFields label="레슨 제목" value={draft.title} onChange={title => setDraft({ ...draft, title })}/><TranslationFields label="레슨 설명" value={draft.description} onChange={description => setDraft({ ...draft, description })}/>
      <div className={s.sectionHeader}><h4>연결된 문제</h4><span>{data.questions.filter(item => item.lessonId === draft.id).length}개</span></div><div className={s.linkedList}>{data.questions.filter(item => item.lessonId === draft.id).sort((a, b) => a.order - b.order).map(question => <button key={question.id} onClick={() => onQuestion(question.id)}><span>{question.order}. {question.code}</span><small>{TYPE_LABEL[question.type]} ↗</small></button>)}{!data.questions.some(item => item.lessonId === draft.id) && <p className={s.muted}>아직 연결된 문제가 없습니다.</p>}</div>
    </div></> : <div className="admin-empty">왼쪽 경로에서 레슨을 선택하세요.</div>}</section>
  </div>;
}

function QuestionsTab({ data, draft, setDraft, select, onSave, onCreate, onDuplicate, onDelete, onReorder, saving }: {
  data: ContentSnapshot; draft: QuestionDraft | null; setDraft: (draft: QuestionDraft) => void; select: (id: string) => void;
  onSave: () => void; onCreate: () => void; onDuplicate: () => void; onDelete: () => void; onReorder: (id: string, target: string) => void; saving: boolean;
}) {
  const [query, setQuery] = useState("");
  const [type, setType] = useState("all");
  const [section, setSection] = useState("all");
  const [unit, setUnit] = useState("all");
  const [lesson, setLesson] = useState("all");
  const [difficulty, setDifficulty] = useState("all");
  const [status, setStatus] = useState("all");
  const [dragId, setDragId] = useState("");
  const filtered = useMemo(() => data.questions.filter(item => {
    const parent = data.lessons.find(row => row.id === item.lessonId);
    return (!query || `${item.code} ${item.answer} ${item.instruction.ko}`.toLowerCase().includes(query.toLowerCase())) &&
      (type === "all" || item.type === type) && (section === "all" || String(parent?.section) === section) &&
      (unit === "all" || String(parent?.unit) === unit) && (lesson === "all" || item.lessonId === lesson) &&
      (difficulty === "all" || String(item.difficulty) === difficulty) && (status === "all" || String(item.isActive) === status);
  }).sort((a, b) => a.lessonId.localeCompare(b.lessonId) || a.order - b.order), [data, query, type, section, unit, lesson, difficulty, status]);
  return <div className={s.questionsPage}>
    <div className="admin-toolbar"><input aria-label="문제 검색" placeholder="코드, 정답, 지시문 검색" value={query} onChange={event => setQuery(event.target.value)}/><select aria-label="유형" value={type} onChange={event => setType(event.target.value)}><option value="all">전체 유형</option>{QUESTION_TYPES.map(item => <option key={item} value={item}>{TYPE_LABEL[item]}</option>)}</select><select aria-label="섹션" value={section} onChange={event => setSection(event.target.value)}><option value="all">전체 섹션</option>{[...new Set(data.lessons.map(item => item.section))].map(item => <option key={item} value={item}>Section {item}</option>)}</select><select aria-label="유닛" value={unit} onChange={event => setUnit(event.target.value)}><option value="all">전체 유닛</option>{[...new Set(data.lessons.map(item => item.unit))].map(item => <option key={item} value={item}>Unit {item}</option>)}</select><select aria-label="레슨" value={lesson} onChange={event => setLesson(event.target.value)}><option value="all">전체 레슨</option>{data.lessons.map(item => <option key={item.id} value={item.id}>{item.title.ko}</option>)}</select><select aria-label="난이도" value={difficulty} onChange={event => setDifficulty(event.target.value)}><option value="all">전체 난이도</option>{[1,2,3,4,5].map(item => <option key={item}>{item}</option>)}</select><select aria-label="상태" value={status} onChange={event => setStatus(event.target.value)}><option value="all">전체 상태</option><option value="true">활성</option><option value="false">비활성</option></select><button className={s.primaryButton} onClick={onCreate}>+ 문제</button></div>
    <div className={s.questionsLayout}>
      <section className="admin-card"><div className="admin-card-head"><h3>문제 목록</h3><span className="admin-pill blue">{filtered.length}개</span></div><div className={s.questionList}>{filtered.length ? filtered.map(item => <button key={item.id} draggable onDragStart={() => setDragId(item.id)} onDragOver={event => event.preventDefault()} onDrop={event => { event.preventDefault(); if (dragId && dragId !== item.id) onReorder(dragId, item.id); setDragId(""); }} className={`${s.questionListItem} ${draft?.id === item.id ? s.selected : ""}`} onClick={() => select(item.id)}><span className={s.questionOrder}>{item.order.toString().padStart(2,"0")}</span><span className={s.questionListText}><strong>{item.code}</strong><small>{TYPE_LABEL[item.type]} · {data.lessons.find(row => row.id === item.lessonId)?.title.ko ?? "연결 없음"}</small></span><span className={item.isActive ? s.statusOn : s.statusOff}>{item.isActive ? "●" : "○"}</span></button>) : <div className="admin-empty">검색 조건에 맞는 문제가 없습니다.</div>}</div><div className={s.listFooter}>드래그하여 같은 레슨 안에서 순서 변경</div></section>
      <section className="admin-card">{draft ? <><div className="admin-card-head"><div><h3>문제 편집기</h3><small className={s.muted}>{draft.code}</small></div><div className={s.actions}><button className={s.button} onClick={onDuplicate}>복제</button><button className={s.button} onClick={onDelete}>삭제</button><button className={s.primaryButton} onClick={onSave} disabled={saving}>저장</button></div></div><div className={s.editorBody}><QuestionEditor data={data} draft={draft} setDraft={setDraft}/></div></> : <div className="admin-empty">문제를 선택하세요.</div>}</section>
      <section className="admin-card"><div className="admin-card-head"><h3>Mobile Preview</h3><span className="admin-pill blue">실시간</span></div>{draft ? <MobilePreview question={draft}/> : <div className="admin-empty">문제를 선택하세요.</div>}</section>
    </div>
  </div>;
}

function QuestionEditor({ data, draft, setDraft }: { data: ContentSnapshot; draft: QuestionDraft; setDraft: (draft: QuestionDraft) => void }) {
  const patch = <K extends keyof QuestionDraft>(key: K, value: QuestionDraft[K]) => setDraft({ ...draft, [key]: value });
  const chips = ["sentence_builder", "translate_builder", "word_arrange", "reply_builder"].includes(draft.type);
  const typing = ["type_answer", "translate_type", "listen_type", "listen_fill"].includes(draft.type);
  const blanks = ["fill_in_blank", "grammar_blank", "listen_fill", "cloze_passage", "type_answer"].includes(draft.type);
  const choice = ["image_choice", "dialog_complete", "listening", "audio_match", "reading_quiz"].includes(draft.type);
  return <div className={s.editorFields}>
    <div className={s.formGrid}><label className="admin-field">코드<input value={draft.code} onChange={event => patch("code", event.target.value)}/></label><label className="admin-field">유형<select value={draft.type} onChange={event => { const next = event.target.value as QuestionType; setDraft({ ...draft, type: next, grading: ["type_answer", "translate_type", "listen_type", "listen_fill"].includes(next) ? draft.grading ?? { mode: "exact", expectedMeaning: "", targetExpressions: [], acceptedAnswers: [] } : undefined }); }}>{QUESTION_TYPES.map(item => <option key={item} value={item}>{TYPE_LABEL[item]} · {item}</option>)}</select></label><label className="admin-field">레슨<select value={draft.lessonId} onChange={event => { const parent = data.lessons.find(item => item.id === event.target.value)!; setDraft({ ...draft, lessonId: parent.id, level: parent.level, lessonCategory: parent.category }); }}>{data.lessons.map(item => <option key={item.id} value={item.id}>S{item.section} U{item.unit} · {item.title.ko}</option>)}</select></label><label className="admin-field">순서<input type="number" min={1} value={draft.order} onChange={event => patch("order", Number(event.target.value))}/></label><label className="admin-field">난이도 1–5<input type="number" min={1} max={5} value={draft.difficulty} onChange={event => patch("difficulty", Number(event.target.value))}/></label><label className="admin-field">상태<select value={String(draft.isActive)} onChange={event => patch("isActive", event.target.value === "true")}><option value="true">활성</option><option value="false">비활성</option></select></label></div>
    <TranslationFields label="지시문" value={draft.instruction} onChange={value => patch("instruction", value)}/>
    {["reply_builder", "dialog_complete", "error_hunt"].includes(draft.type) && <label className="admin-field">NPC 말풍선 (한국어)<textarea value={draft.npcText} onChange={event => patch("npcText", event.target.value)}/></label>}
    {["translate_builder", "translate_type", "type_answer", "sentence_builder"].includes(draft.type) && <TranslationFields label="정답의 번역 · 학습자 언어 프롬프트" value={draft.answerTranslation} onChange={value => patch("answerTranslation", value)}/>}
    <label className="admin-field">정답<input value={draft.answer} onChange={event => patch("answer", event.target.value)}/></label>
    {chips && <><label className="admin-field">한국어 칩 · 한 줄에 하나<textarea value={join(draft.options)} onChange={event => patch("options", split(event.target.value))}/></label>{draft.type === "sentence_builder" && <><TranslationFields label="언어별 조립 정답" value={draft.answerI18n} onChange={value => patch("answerI18n", value)}/><fieldset className={s.translations}><legend>언어별 칩</legend><div className={s.translationGrid}>{LANGUAGES.map(lang => <label key={lang} className="admin-field">{lang.toUpperCase()} · 한 줄에 하나<textarea value={join(draft.optionsI18n[lang])} onChange={event => patch("optionsI18n", { ...draft.optionsI18n, [lang]: split(event.target.value) })}/></label>)}</div></fieldset></>}</>}
    {choice && <fieldset className={s.translations}><legend>선택지 · 오답 포함</legend>{[0,1,2,3].map(index => { const current = draft.choices[index] ?? { text: "", label: "", emoji: "", imageUrl: "" }; const update = (key: keyof typeof current, value: string) => { const next = [...draft.choices]; next[index] = { ...current, [key]: value }; patch("choices", next); }; return <div className={s.choiceRow} key={index}><span>{index + 1}</span><input aria-label={`${index + 1}번 한국어`} placeholder="한국어 선택지" value={current.text} onChange={event => update("text", event.target.value)}/><input aria-label={`${index + 1}번 번역`} placeholder="표시 라벨" value={current.label} onChange={event => update("label", event.target.value)}/><input aria-label={`${index + 1}번 이모지`} placeholder="이모지" value={current.emoji} onChange={event => update("emoji", event.target.value)}/></div>; })}</fieldset>}
    {["word_matching", "audio_match"].includes(draft.type) && <label className="admin-field">매칭 쌍 · 한 줄에 `한국어 | 학습자 언어`<textarea value={draft.pairs.map(pair => `${pair.korean} | ${pair.native}`).join("\n")} onChange={event => patch("pairs", event.target.value.split("\n").filter(Boolean).map(line => { const [korean = "", native = ""] = line.split("|"); return { korean: korean.trim(), native: native.trim() }; }))}/></label>}
    {["dialog_complete", "dialog_order"].includes(draft.type) && <label className="admin-field">대화 줄 · 한 줄에 `npc | 대사` 또는 `user | 대사`<textarea value={draft.dialogLines.map(line => `${line.speaker} | ${line.text}`).join("\n")} onChange={event => patch("dialogLines", event.target.value.split("\n").filter(Boolean).map(line => { const [speaker = "npc", text = ""] = line.split("|"); return { speaker: speaker.trim() === "user" ? "user" as const : "npc" as const, text: text.trim() }; }))}/></label>}
    {blanks && <><label className="admin-field">빈칸 문장 템플릿 · ___ 사용<input value={draft.sentenceTemplate} onChange={event => patch("sentenceTemplate", event.target.value)}/></label><label className="admin-field">빈칸 정답 · 한 줄에 하나<textarea value={join(draft.blankAnswers)} onChange={event => patch("blankAnswers", split(event.target.value))}/></label></>}
    {["fill_in_blank", "image_choice", "type_answer"].includes(draft.type) && <div className={s.formGrid}><label className="admin-field">빈칸 앞 문장<input value={draft.sentencePrefix} onChange={event => patch("sentencePrefix", event.target.value)}/></label><label className="admin-field">빈칸 뒤 문장<input value={draft.sentenceSuffix} onChange={event => patch("sentenceSuffix", event.target.value)}/></label></div>}
    {draft.type === "grammar_build" && <label className="admin-field">조립 행 · 한 줄에 `정답 | 보기1, 보기2`<textarea value={draft.buildRows.map(row => `${row.correct} | ${row.options.join(", ")}`).join("\n")} onChange={event => patch("buildRows", event.target.value.split("\n").filter(Boolean).map(line => { const [correct = "", options = ""] = line.split("|"); return { correct: correct.trim(), options: options.split(",").map(value => value.trim()).filter(Boolean) }; }))}/></label>}
    {["listening", "listen_type", "listen_fill", "sentence_builder", "speaking", "word_arrange"].includes(draft.type) && <label className="admin-field">TTS 원문<input value={draft.audioText} onChange={event => patch("audioText", event.target.value)}/></label>}
    {["listening", "listen_type", "listen_fill", "sentence_builder", "speaking", "word_arrange", "audio_match"].includes(draft.type) && <label className="admin-field">오디오 URL<input value={draft.audioUrl} onChange={event => patch("audioUrl", event.target.value)}/></label>}
    {draft.type === "image_choice" && <label className="admin-field">대표 이미지 URL<input value={draft.imageUrl} onChange={event => patch("imageUrl", event.target.value)}/></label>}
    {["reading_quiz", "cloze_passage"].includes(draft.type) && <><label className="admin-field">지문 제목<input value={draft.passageTitle} onChange={event => patch("passageTitle", event.target.value)}/></label><label className="admin-field">지문<textarea value={draft.passage} onChange={event => patch("passage", event.target.value)}/></label></>}
    {draft.type === "error_hunt" && <label className="admin-field">오류 단어<input value={draft.wrongWord} onChange={event => patch("wrongWord", event.target.value)}/></label>}
    {draft.type === "verb_transform" && <div className={s.formGrid}><label className="admin-field">기본형<input value={draft.baseWord} onChange={event => patch("baseWord", event.target.value)}/></label><label className="admin-field">목표 형태<input value={draft.targetForm} onChange={event => patch("targetForm", event.target.value)}/></label></div>}
    {typing && draft.grading && <fieldset className={s.translations}><legend>타이핑 채점</legend><div className={s.formGrid}><label className="admin-field">모드<select value={draft.grading.mode} onChange={event => patch("grading", { ...draft.grading!, mode: event.target.value as NonNullable<QuestionDraft["grading"]>["mode"] })}><option value="exact">exact</option><option value="semantic">semantic</option><option value="targetExpression">targetExpression</option></select></label><label className="admin-field">의미<input value={draft.grading.expectedMeaning} onChange={event => patch("grading", { ...draft.grading!, expectedMeaning: event.target.value })}/></label></div><label className="admin-field">허용 답안 · 한 줄에 하나<textarea value={join(draft.grading.acceptedAnswers)} onChange={event => patch("grading", { ...draft.grading!, acceptedAnswers: split(event.target.value) })}/></label></fieldset>}
    <label className="admin-field">추가 허용 표기 · 한 줄에 하나<textarea value={join(draft.acceptedAnswers)} onChange={event => patch("acceptedAnswers", split(event.target.value))}/></label>
    <TranslationFields label="힌트" value={draft.hint} onChange={value => patch("hint", value)}/><TranslationFields label="정답 설명" value={draft.explanation} onChange={value => patch("explanation", value)}/>
    <div className={s.formGrid}><label className="admin-field">태그 · 쉼표 구분<input value={draft.tags.join(", ")} onChange={event => patch("tags", event.target.value.split(",").map(value => value.trim()).filter(Boolean))}/></label><label className="admin-field">XP<input type="number" min={0} value={draft.xpReward} onChange={event => patch("xpReward", Number(event.target.value))}/></label></div>
  </div>;
}

function MobilePreview({ question }: { question: QuestionDraft }) {
  const [language, setLanguage] = useState<"uz" | "en" | "ru">("uz");
  const isChip = ["translate_builder", "word_arrange", "reply_builder", "sentence_builder"].includes(question.type);
  const prompt = question.type === "reply_builder" ? question.npcText : question.type === "sentence_builder" ? question.audioText || question.answer : question.answerTranslation[language] || question.npcText;
  return <div className={s.previewOuter}><div className={s.previewControls}><span>390 × 720 · KORIO 학습 화면</span><select aria-label="미리보기 언어" value={language} onChange={event => setLanguage(event.target.value as typeof language)}><option value="uz">UZ</option><option value="en">EN</option><option value="ru">RU</option></select></div><div className={s.phone}><div className={s.phoneTop}><span>‹</span><div><i style={{ width: "58%" }}/></div><span>♥ ♥ ♥</span></div><div className={s.phoneBody}><small>QUESTION {question.order} · {TYPE_LABEL[question.type]}</small><h4>{question.instruction[language] || question.instruction.ko}</h4>{prompt && <div className={s.speechBubble}>{prompt}</div>}{question.sentenceTemplate && <div className={s.sentence}>{question.sentenceTemplate}</div>}{question.passage && <div className={s.sentence}>{question.passage}</div>}{question.dialogLines.length > 0 && <div className={s.sentence}>{question.dialogLines.map((line, index) => <p key={index}><strong>{line.speaker === "npc" ? "상대" : "나"}:</strong> {line.text}</p>)}</div>}{question.pairs.length > 0 ? <div className={s.previewChoices}>{question.pairs.map((pair, index) => <div key={index}>{pair.korean}<small>{pair.native}</small></div>)}</div> : question.choices.length > 0 ? <div className={s.previewChoices}>{question.choices.map((choice, index) => <div key={index}>{choice.emoji && <span>{choice.emoji}</span>}{choice.text}<small>{choice.label}</small></div>)}</div> : isChip ? <div className={s.chips}>{(question.type === "sentence_builder" ? question.optionsI18n[language] : question.options).map((chip, index) => <span key={`${chip}-${index}`}>{chip}</span>)}</div> : <div className={s.previewInput}>{["type_answer", "translate_type", "listen_type", "listen_fill"].includes(question.type) ? "정답을 입력하세요…" : "답을 선택하세요…"}</div>}{question.hint[language] && <p className={s.previewHint}>힌트: {question.hint[language]}</p>}</div><div className={s.phoneBottom}>확인하기</div></div><p className={s.previewNote}>실제 앱을 완전히 재현한 화면은 아니며, mock 편집 내용 확인용입니다.</p></div>;
}

function qualityIssues(question: QuestionDraft, data: ContentSnapshot): string[] {
  const issues: string[] = [];
  if (!question.answer.trim() && !question.blankAnswers.some(Boolean)) issues.push("정답 없음");
  if (["translate_builder", "word_arrange", "reply_builder", "sentence_builder"].includes(question.type) && !question.options.length) issues.push("칩 없음");
  if (["translate_builder", "word_arrange", "reply_builder"].includes(question.type) && question.options.length > 0 && question.options.every(option => question.answer.includes(option))) issues.push("오답 칩 없음");
  if (question.type === "image_choice" && question.choices.filter(item => item.text.trim()).length < 4) issues.push("선택지 부족");
  if (question.type === "image_choice" && !question.choices.some(item => item.text === question.answer)) issues.push("정답 선택지 없음");
  if (question.type === "image_choice" && !question.choices.some(item => item.text && item.text !== question.answer)) issues.push("오답 없음");
  if (["word_matching", "audio_match"].includes(question.type) && question.pairs.length < 2) issues.push("매칭 쌍 부족");
  if (["type_answer", "translate_type", "listen_type", "listen_fill"].includes(question.type) && !question.grading) issues.push("채점 규칙 없음");
  if (question.type === "grammar_build" && !question.buildRows.length) issues.push("조립 행 없음");
  if (["reading_quiz", "cloze_passage"].includes(question.type) && !question.passage.trim()) issues.push("지문 없음");
  if (question.difficulty < 1 || question.difficulty > 5) issues.push("난이도 범위 오류");
  if (!data.lessons.some(item => item.id === question.lessonId)) issues.push("레슨 연결 끊김");
  if (question.isActive && data.lessons.find(item => item.id === question.lessonId)?.isActive === false) issues.push("비활성 레슨 참조");
  if (LANGUAGES.some(lang => !question.instruction[lang].trim())) issues.push("지시문 번역 누락");
  if (data.questions.some(item => item.id !== question.id && item.answer && item.answer === question.answer && item.type === question.type)) issues.push("중복 정답·유형");
  return issues;
}

function QualityTab({ data, onQuestion }: { data: ContentSnapshot; onQuestion: (id: string) => void }) {
  const [group, setGroup] = useState("all");
  const quality = data.questions.map(item => ({ item, issues: qualityIssues(item, data) }));
  const visible = quality.filter(({ item, issues }) => group === "all" || (group === "issues" && issues.length) || (group === "easy" && item.metrics.attempts > 0 && item.metrics.correctRate >= 90) || (group === "hard" && item.metrics.attempts > 0 && item.metrics.correctRate <= 45) || (group === "drop" && item.metrics.dropOffRate >= 12) || (group === "problem" && issues.length > 0 && (item.metrics.correctRate <= 50 || item.metrics.skipRate >= 10)));
  const byType = QUESTION_TYPES.map(type => ({ type, values: data.questions.filter(item => item.type === type && item.metrics.attempts > 0) })).filter(item => item.values.length);
  return <div className={s.stack}>
    <div className="admin-grid four"><div className="admin-card admin-kpi"><div className="admin-kpi-label">검토 필요</div><div className="admin-kpi-value">{quality.filter(item => item.issues.length).length}</div><div className="admin-kpi-note">자동 검사 결과</div></div><div className="admin-card admin-kpi"><div className="admin-kpi-label">Too Easy</div><div className="admin-kpi-value">{quality.filter(({ item }) => item.metrics.attempts && item.metrics.correctRate >= 90).length}</div><div className="admin-kpi-note">정답률 90% 이상</div></div><div className="admin-card admin-kpi"><div className="admin-kpi-label">Too Hard</div><div className="admin-kpi-value">{quality.filter(({ item }) => item.metrics.attempts && item.metrics.correctRate <= 45).length}</div><div className="admin-kpi-note">정답률 45% 이하</div></div><div className="admin-card admin-kpi"><div className="admin-kpi-label">High Drop-off</div><div className="admin-kpi-value">{quality.filter(({ item }) => item.metrics.dropOffRate >= 12).length}</div><div className="admin-kpi-note">문항 직후 이탈 12% 이상</div></div></div>
    <div className="admin-grid"><section className="admin-card"><div className="admin-card-head"><h3>유형별 정답률</h3><span className="admin-pill">mock 시도 데이터</span></div><div className="admin-card-body">{byType.map(({ type, values }) => { const rate = Math.round(values.reduce((sum, item) => sum + item.metrics.correctRate, 0) / values.length); return <div className="admin-hbar" key={type}><span className="admin-hbar-label">{TYPE_LABEL[type]}</span><div className="admin-hbar-track"><span style={{ width: `${rate}%` }}/></div><span className="admin-hbar-value">{rate}%</span></div>; })}</div></section><section className="admin-card"><div className="admin-card-head"><h3>품질 판단 기준</h3></div><div className="admin-card-body"><p className={s.prose}>정답·오답 보기·타입별 필수 필드·난이도·번역·레슨 연결을 점검합니다. 정답률과 이탈률은 mock 시도 데이터를 사용합니다.</p><p className={s.prose}>시도 수가 0인 문제는 쉬움/어려움 판정에서 제외합니다. 실제 API 연결 시 QuestionAttempt와 LessonAttempt 집계로 교체합니다.</p></div></section></div>
    <section className="admin-card"><div className="admin-card-head"><h3>문제 진단</h3><select className={s.select} aria-label="품질 그룹" value={group} onChange={event => setGroup(event.target.value)}><option value="all">전체</option><option value="issues">스키마·번역 이슈</option><option value="easy">Too Easy</option><option value="hard">Too Hard</option><option value="drop">High Drop-off</option><option value="problem">Problematic</option></select></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>문제</th><th>유형</th><th>진단</th><th>시도</th><th>정답률</th><th>오답률</th><th>Skip</th><th>평균 풀이</th><th>이탈</th></tr></thead><tbody>{visible.map(({ item, issues }) => <tr key={item.id}><td><button className="linklike" onClick={() => onQuestion(item.id)}>{item.code}</button></td><td>{TYPE_LABEL[item.type]}</td><td>{issues.length ? issues.map(issue => <span key={issue} className="admin-pill warn">{issue}</span>) : <span className="admin-pill good">정상</span>}</td><td>{item.metrics.attempts}</td><td>{item.metrics.attempts ? `${item.metrics.correctRate}%` : "—"}</td><td>{item.metrics.attempts ? `${(100 - item.metrics.correctRate - item.metrics.skipRate).toFixed(1)}%` : "—"}</td><td>{item.metrics.attempts ? `${item.metrics.skipRate}%` : "—"}</td><td>{item.metrics.attempts ? `${(item.metrics.avgDurationMs / 1000).toFixed(1)}초` : "—"}</td><td>{item.metrics.attempts ? `${item.metrics.dropOffRate}%` : "—"}</td></tr>)}</tbody></table>{!visible.length && <div className="admin-empty">이 그룹에 해당하는 문제가 없습니다.</div>}</div></section>
  </div>;
}

function LibraryTab({ data, draft, setDraft, select, onSave, saving }: { data: ContentSnapshot; draft: LibraryItem | null; setDraft: (draft: LibraryItem) => void; select: (id: string) => void; onSave: () => void; saving: boolean }) {
  const [kind, setKind] = useState<LibraryItem["kind"]>("grammar");
  const [query, setQuery] = useState("");
  const rows = data.library.filter(item => item.kind === kind && `${item.id} ${item.kind === "grammar" ? item.pattern : item.kind === "expression" ? item.korean : item.char}`.toLowerCase().includes(query.toLowerCase()));
  const selectKind = (next: LibraryItem["kind"]) => { setKind(next); const first = data.library.find(item => item.kind === next); if (first) select(first.id); };
  return <div className={s.stack}><div className="admin-toolbar"><div className={s.segmented}>{(["grammar", "expression", "hangul"] as const).map(item => <button key={item} className={kind === item ? s.segmentActive : ""} onClick={() => selectKind(item)}>{item === "grammar" ? "Grammar" : item === "expression" ? "Expressions" : "Hangul"}</button>)}</div><input aria-label="콘텐츠 검색" value={query} onChange={event => setQuery(event.target.value)} placeholder="코드, 제목, 글자 검색"/></div><div className={s.pathLayout}><section className="admin-card"><div className="admin-card-head"><h3>{kind === "grammar" ? "문법" : kind === "expression" ? "표현" : "한글"} 목록</h3><span className="admin-pill blue">{rows.length}개</span></div><div className={s.libraryList}>{rows.map(item => <button key={item.id} className={`${s.libraryItem} ${draft?.id === item.id ? s.selected : ""}`} onClick={() => select(item.id)}><strong>{item.kind === "grammar" ? item.pattern : item.kind === "expression" ? item.korean : `${item.char} ${item.name}`}</strong><small>{item.kind === "hangul" ? item.id : item.code} {item.kind !== "hangul" && `· S${item.section} U${item.unit}`}</small></button>)}{!rows.length && <div className="admin-empty">검색 결과가 없습니다.</div>}</div></section><section className="admin-card">{draft && draft.kind === kind ? <><div className="admin-card-head"><div><h3>{draft.kind === "grammar" ? draft.pattern : draft.kind === "expression" ? draft.korean : draft.char}</h3><small className={s.muted}>{draft.kind === "hangul" ? draft.id : draft.code}</small></div><button className={s.primaryButton} onClick={onSave} disabled={saving}>저장</button></div><div className="admin-card-body"><LibraryEditor draft={draft} setDraft={setDraft} data={data}/></div></> : <div className="admin-empty">목록에서 콘텐츠를 선택하세요.</div>}</section></div></div>;
}

function LibraryEditor({ draft, setDraft, data }: { draft: LibraryItem; setDraft: (draft: LibraryItem) => void; data: ContentSnapshot }) {
  if (draft.kind === "hangul") return <div className={s.editorFields}><p className={s.prose}>한글 자모는 모바일 고정 콘텐츠이며, ID는 서버 진행도의 키입니다. 이 mock 편집은 브라우저에서만 작동합니다.</p><div className={s.formGrid}><label className="admin-field">글자<input value={draft.char} onChange={event => setDraft({ ...draft, char: event.target.value })}/></label><label className="admin-field">이름<input value={draft.name} onChange={event => setDraft({ ...draft, name: event.target.value })}/></label><label className="admin-field">로마자<input value={draft.romanization} onChange={event => setDraft({ ...draft, romanization: event.target.value })}/></label><label className="admin-field">구분<input value={draft.category} disabled/></label></div><label className="admin-field">예시 단어 · 한 줄에 하나<textarea value={draft.examples.map(item => `${item.word} | ${item.romanization}`).join("\n")} onChange={event => setDraft({ ...draft, examples: event.target.value.split("\n").filter(Boolean).map(line => { const [word = "", romanization = ""] = line.split("|"); return { word: word.trim(), romanization: romanization.trim() }; }) })}/></label></div>;
  const linked = data.lessons.filter(item => draft.kind === "grammar" ? item.grammarCode === draft.code : item.section === draft.section && item.unit === draft.unit);
  return <div className={s.editorFields}><div className={s.formGrid}><label className="admin-field">코드<input value={draft.code} onChange={event => setDraft({ ...draft, code: event.target.value } as LibraryItem)}/></label><label className="admin-field">{draft.kind === "grammar" ? "문법 패턴" : "한국어 표현"}<input value={draft.kind === "grammar" ? draft.pattern : draft.korean} onChange={event => setDraft(draft.kind === "grammar" ? { ...draft, pattern: event.target.value } : { ...draft, korean: event.target.value })}/></label><label className="admin-field">Section<input type="number" min={1} value={draft.section} onChange={event => setDraft({ ...draft, section: Number(event.target.value) } as LibraryItem)}/></label><label className="admin-field">Unit<input type="number" min={1} value={draft.unit} onChange={event => setDraft({ ...draft, unit: Number(event.target.value) } as LibraryItem)}/></label><label className="admin-field">순서<input type="number" min={1} value={draft.order} onChange={event => setDraft({ ...draft, order: Number(event.target.value) } as LibraryItem)}/></label><label className="admin-field">상태<select value={String(draft.isActive)} onChange={event => setDraft({ ...draft, isActive: event.target.value === "true" } as LibraryItem)}><option value="true">활성</option><option value="false">비활성</option></select></label></div>{draft.kind === "grammar" ? <><TranslationFields label="요약" value={draft.summary} onChange={summary => setDraft({ ...draft, summary } as GrammarItem)}/><TranslationFields label="설명" value={draft.explanation} onChange={explanation => setDraft({ ...draft, explanation } as GrammarItem)}/></> : <><div className={s.formGrid}><label className="admin-field">Pack 코드<input value={draft.packCode} onChange={event => setDraft({ ...draft, packCode: event.target.value } as ExpressionItem)}/></label><label className="admin-field">Node 코드<input value={draft.nodeCode} onChange={event => setDraft({ ...draft, nodeCode: event.target.value } as ExpressionItem)}/></label></div><TranslationFields label="뜻" value={draft.meaning} onChange={meaning => setDraft({ ...draft, meaning } as ExpressionItem)}/><TranslationFields label="사용 맥락" value={draft.context} onChange={context => setDraft({ ...draft, context } as ExpressionItem)}/></>}<div className={s.sectionHeader}><h4>연결 위치</h4></div><p className={s.prose}>Section {draft.section} → Unit {draft.unit} · 연결 레슨 {linked.map(item => item.title.ko).join(", ") || "없음"}</p></div>;
}

function LocalizationTab({ data, onQuestion, onLibrary, onLesson }: { data: ContentSnapshot; onQuestion: (id: string) => void; onLibrary: (id: string) => void; onLesson: (id: string) => void }) {
  const [query, setQuery] = useState("");
  const [missingOnly, setMissingOnly] = useState(false);
  type LocalizationRow = { id: string; kind: "lesson" | "question" | "grammar" | "expression"; title: string; code: string; value: LocalizedText };
  const rows: LocalizationRow[] = [
    ...data.lessons.flatMap(item => ([
      { id: item.id, kind: "lesson" as const, title: item.title.ko, code: `${item.code} · 제목`, value: item.title },
      { id: item.id, kind: "lesson" as const, title: item.title.ko, code: `${item.code} · 설명`, value: item.description },
    ])),
    ...data.questions.flatMap(item => ([
      { id: item.id, kind: "question" as const, title: item.instruction.ko, code: `${item.code} · 지시문`, value: item.instruction },
      ...(["translate_builder", "translate_type", "type_answer", "sentence_builder", "reply_builder"].includes(item.type)
        ? [{ id: item.id, kind: "question" as const, title: item.instruction.ko, code: `${item.code} · 정답 번역`, value: item.answerTranslation }] : []),
      ...(item.type === "sentence_builder" ? [{ id: item.id, kind: "question" as const, title: item.instruction.ko, code: `${item.code} · 조립 정답`, value: item.answerI18n }] : []),
    ])),
    ...data.library.filter((item): item is GrammarItem | ExpressionItem => item.kind !== "hangul").flatMap((item): LocalizationRow[] => item.kind === "grammar" ? [
      { id: item.id, kind: item.kind, title: item.pattern, code: `${item.code} · 요약`, value: item.summary },
      { id: item.id, kind: item.kind, title: item.pattern, code: `${item.code} · 설명`, value: item.explanation },
    ] : [
      { id: item.id, kind: item.kind, title: item.korean, code: `${item.code} · 뜻`, value: item.meaning },
      { id: item.id, kind: item.kind, title: item.korean, code: `${item.code} · 맥락`, value: item.context },
    ]),
  ];
  const filtered = rows.filter(item => (!query || `${item.title} ${item.code}`.toLowerCase().includes(query.toLowerCase())) && (!missingOnly || coverage(item.value) < 4));
  const all = rows.length * LANGUAGES.length;
  const filled = rows.reduce((sum, item) => sum + coverage(item.value), 0);
  return <div className={s.stack}><div className="admin-grid three"><div className="admin-card admin-kpi"><div className="admin-kpi-label">번역 적용률</div><div className="admin-kpi-value">{all ? Math.round(filled / all * 100) : 0}%</div><div className={s.coverageTrack}><span style={{ width: `${all ? filled / all * 100 : 0}%` }}/></div></div><div className="admin-card admin-kpi"><div className="admin-kpi-label">번역 누락 필드</div><div className="admin-kpi-value">{rows.filter(item => coverage(item.value) < 4).length}</div><div className="admin-kpi-note">클릭하면 해당 편집기로 이동</div></div><div className="admin-card admin-kpi"><div className="admin-kpi-label">확인 대상 필드</div><div className="admin-kpi-value">{rows.length}</div><div className="admin-kpi-note">레슨 · 문제 · 문법 · 표현</div></div></div><div className="admin-toolbar"><input aria-label="번역 검색" value={query} onChange={event => setQuery(event.target.value)} placeholder="코드 또는 원문 검색"/><button className={missingOnly ? "is-active" : ""} onClick={() => setMissingOnly(!missingOnly)}>번역 누락만</button></div><section className="admin-card"><div className="admin-card-head"><h3>언어별 번역 상태</h3><span className="admin-pill blue">KO · UZ · EN · RU</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>콘텐츠</th><th>유형</th><th>KO</th><th>UZ</th><th>EN</th><th>RU</th><th>적용률</th></tr></thead><tbody>{filtered.map(item => <tr key={`${item.kind}-${item.id}-${item.code}`}><td><button className="linklike" onClick={() => item.kind === "lesson" ? onLesson(item.id) : item.kind === "question" ? onQuestion(item.id) : onLibrary(item.id)}>{item.title || item.code}</button><small className={s.codeLine}>{item.code}</small></td><td>{item.kind}</td>{LANGUAGES.map(lang => <td key={lang}><span className={`admin-pill ${item.value[lang].trim() ? "good" : "warn"}`}>{item.value[lang].trim() ? "✓ 완료" : "⚠ 누락"}</span></td>)}<td>{Math.round(coverage(item.value) / 4 * 100)}%</td></tr>)}</tbody></table>{!filtered.length && <div className="admin-empty">검색 결과가 없습니다.</div>}</div></section><p className={s.muted}>mock 저장소에 포함된 번역 필드를 검사합니다. API 연결 시 다른 학습 콘텐츠의 번역 필드도 추가할 수 있습니다.</p></div>;
}
